/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_flirora_caxton_dll_CaxtonInternal */

#ifndef _Included_xyz_flirora_caxton_dll_CaxtonInternal
#define _Included_xyz_flirora_caxton_dll_CaxtonInternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    createFont
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_createFont
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    destroyFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_destroyFont
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontGlyphIndex
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontGlyphIndex
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontMetrics
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontMetrics
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontAtlasSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontAtlasSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontAtlasLocations
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontAtlasLocations
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontBboxes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontBboxes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontAtlasNumPages
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontAtlasNumPages
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    fontAtlasPage
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_fontAtlasPage
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    configureFont
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_configureFont
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    destroyConfiguredFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_destroyConfiguredFont
  (JNIEnv *, jclass, jlong);

/*
 * Class:     xyz_flirora_caxton_dll_CaxtonInternal
 * Method:    shape
 * Signature: (J[C[I)[Lxyz/flirora/caxton/layout/ShapingResult;
 */
JNIEXPORT jobjectArray JNICALL Java_xyz_flirora_caxton_dll_CaxtonInternal_shape
  (JNIEnv *, jclass, jlong, jcharArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
